### ISSUE TITLE
heisenbridge cannot start since my last update

### ISSUE THREAD

**Issue by blastrock** [hifi/heisenbridge#183]
Hi there,

I'm using heisenbridge from the latest docker, and it stopped working since I updated it.

Here is the log

```
Heisenbridge v1.7.1.dev2+g2ae32c2
Traceback (most recent call last):
  File "/opt/heisenbridge/heisenbridge/__main__.py", line 433, in run
    is_admin = await self.api.request(Method.GET, SynapseAdminPath.v1.users[self.user_id].admin)
  File "/usr/local/lib/python3.9/site-packages/mautrix/api.py", line 306, in request
    return await self._send(method, full_url, content, query_params, headers or {})
  File "/usr/local/lib/python3.9/site-packages/mautrix/api.py", line 224, in _send
    raise make_request_error(http_status=response.status,
mautrix.errors.request.MatrixUnknownRequestError: 404: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.21.4</center>
</body>
</html>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/heisenbridge/heisenbridge/__main__.py", line 679, in <module>
    main()
  File "/opt/heisenbridge/heisenbridge/__main__.py", line 674, in main
    loop.run_until_complete(service.run(args.listen_address, args.listen_port, args.homeserver, args.owner))
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/heisenbridge/heisenbridge/__main__.py", line 438, in run
    logging.exception()
TypeError: exception() missing 1 required positional argument: 'msg'
```

From what I can see in the code, the exception is not supposed to be fatal, but because of the call to `logging.exception()`, the program crashes.

Btw, do you know why that particular call returns 404?

**Comment by hifi** [comment]
I pushed a fix to master, latest image should be updated now and that invalid `logging.exception()` call completely removed.

That endpoint will likely return 404 if you use a proxy or your public endpoint as the homeserver address in Heisenbridge command line and you don't have the Synapse admin API available through it or you're not running Synapse in the first place. It's fine it doesn't exist as the bridge would in addition to having access to the API also need full admin privileges to force any local user (IRC ghost in this case) to any local room.

If you don't have any reason to use the public endpoint with the bridge (they run within the same host system or private network) I suggest you change it regardless.

The latest image is not really considered stable and I haven't had the guts to run it myself yet because of major refactors so thanks for testing :+1: :sweat_smile:

**Comment by blastrock** [comment]
Thanks for the quick response! I pulled the latest image and it fixes my issue.

Also thanks for the explanation, I was indeed using a reverse proxy. I thought the bridges needed to know the public address of the server, but it works with the internal one as you suggested.

> The latest image is not really considered stable and I haven't had the guts to run it myself yet because of major refactors so thanks for testing

Well, you're welcome. It would be nice to have a `stable` tag on those images though ^^
