### ISSUE TITLE
Commands from FluffyChat are ignored 

### ISSUE THREAD

**Issue by hifi** [hifi/heisenbridge#207]
Somethings up.

**Comment by dahrens** [comment]
Looks like I triggered the same or an related issue using cinny. After setting up element-desktop (+ cross signing, since it comes along with it on start-up) and creating a fresh DM conversation with heisenbridge it started answering me. Although I was unable to verify the cinny device/session - heisenbridge was willing to talk to me through cinny afterwards as well.
