### ISSUE TITLE
Correct AUTOCMD example

### ISSUE THREAD

**Issue by jgoerzen** [hifi/heisenbridge#47]
Hi,

Thanks for Heisenbridge!

The `AUTOCMD -h` output includes:

`Example: AUTOCMD msg Q@CServe.quakenet.org :auth foo bar`

This is a bit confusing, and the `msg` syntax wasn't working for me.  I had to use this for a Nickserv network:

`AUTOCMD PRIVMSG nickserv :identify mynick mypassword`

So, `PRIVMSG` instead of `msg`, and no `@...` as part of the nick.

**Comment by hifi** [comment]
Indeed, the example is wrong. I'd want to change it to use commands instead of raw messages anyway as it's a bit awkward to use `PRIVMSG` with colon and all but I'll update the example at least.

On some NickServ networks you can also use the `PASSWORD` setting so it sets the server password on connect to avoid using `AUTOCMD`.

**Comment by jgoerzen** [comment]
I personally don't mind PRIVMSG but then I've been IRCing for 
quite some time; some networks use quite odd ways of identifying 
(that may not be a PRIVMSG).

I've seen server passwords too, but they aren't supported by all 
Nickserv networks (a subset of them).

SASL auth is also a thing nowadays but it seems to be optional 
everywhere I've seen it.

Thanks again!

**Comment by hifi** [comment]
AUTOCMD is now using the correct format for commands and the help has been updated. There's no automatic migration so it will complain about using PRIVMSG.

Sorry.
